export const MESSAGE_TYPES = {
    RESPONSE_LIFECYCLE: 'BLACKIYA_RESPONSE_LIFECYCLE',
    RESPONSE_FINISHED: 'BLACKIYA_RESPONSE_FINISHED',
    STREAM_DELTA: 'BLACKIYA_STREAM_DELTA',
    CONVERSATION_ID_RESOLVED: 'BLACKIYA_CONVERSATION_ID_RESOLVED',
    ATTEMPT_DISPOSED: 'BLACKIYA_ATTEMPT_DISPOSED',
    STREAM_DUMP_CONFIG: 'BLACKIYA_STREAM_DUMP_CONFIG',
    TITLE_RESOLVED: 'BLACKIYA_TITLE_RESOLVED',
    STREAM_DUMP_FRAME: 'BLACKIYA_STREAM_DUMP_FRAME',
    SESSION_INIT: 'BLACKIYA_SESSION_INIT',
    CAPTURE_DATA_INTERCEPTED: 'LLM_CAPTURE_DATA_INTERCEPTED',
    LOG_ENTRY: 'LLM_LOG_ENTRY',
    PAGE_SNAPSHOT_REQUEST: 'BLACKIYA_PAGE_SNAPSHOT_REQUEST',
    PAGE_SNAPSHOT_RESPONSE: 'BLACKIYA_PAGE_SNAPSHOT_RESPONSE',
} as const;

export type MessageType = (typeof MESSAGE_TYPES)[keyof typeof MESSAGE_TYPES];
